name: invite-remake
version: '${project.version}'
main: me.vaaz.invitehim.ReferenceBootstrap
api-version: '1.20'

authors:
  - vaaaz
  - syncwrld

commands:
  ref:
    aliases:
      - reference
  convites:
    aliases:
      - invites
  codigo:
    aliases:
      - code
  mudarcodigo:
    aliases:
      - changecode
